.onAttach <- function(...) {
  invisible()
}

#' bamcheckr: tools for working with bamcheck files
#'
#' bamcheckr provides tools that can read and write bamcheck files (as 
#' generated by samtools) as well as utilities for generating additional 
#' summary statistics (e.g. based on shapes of distributions).
#' 
#' @name bamcheckr
#' @docType package
#' @name bamcheckr
NULL

.onLoad <- function(libname, pkgname) {
  invisible()
}